/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JekyllBlogManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/views/BlogListView.ts
var import_obsidian2 = require("obsidian");

// src/utils/text.ts
var getReadingTime = (wordCount) => {
  const minutes = Math.ceil(wordCount / 200);
  return minutes === 1 ? "1 min read" : `${minutes} min read`;
};
var titleToFilename = (title) => {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") + ".md";
};
var extractExcerpt = (content, wordLimit = 20) => {
  const words = content.split(/\s+/).filter((w) => w.length > 0);
  return words.slice(0, wordLimit).join(" ") + (words.length > wordLimit ? "..." : "");
};

// src/services/post.ts
function createPostService(app) {
  const { vault, metadataCache } = app;
  const parsePost = async (file, isDraft) => {
    try {
      const content = await vault.read(file);
      const cache = metadataCache.getFileCache(file);
      const frontmatter = cache == null ? void 0 : cache.frontmatter;
      let title = file.basename.replace(/^\d{4}-\d{2}-\d{2}-/, "");
      let date = "";
      if (frontmatter) {
        if (frontmatter.title) {
          title = String(frontmatter.title);
        }
        if (frontmatter.date) {
          date = String(frontmatter.date);
        }
      }
      const filenameDate = file.name.match(/^(\d{4}-\d{2}-\d{2})/);
      if (!date && filenameDate) {
        date = filenameDate[1];
      }
      const bodyContent = content.replace(/^---\n[\s\S]*?\n---\n/, "").trim();
      const wordCount = bodyContent.split(/\s+/).filter((w) => w.length > 0).length;
      const excerpt = extractExcerpt(bodyContent, 20);
      return {
        file,
        filename: file.name,
        title,
        date,
        isDraft,
        wordCount,
        excerpt
      };
    } catch (error) {
      console.error("Error parsing post:", error);
      return null;
    }
  };
  const loadPosts = async () => {
    const markdownFiles = vault.getMarkdownFiles();
    const blogFiles = markdownFiles.filter(
      (file) => file.path.startsWith("_drafts") || file.path.startsWith("_posts")
    );
    console.log(markdownFiles, blogFiles);
    const posts = [];
    for (const file of blogFiles) {
      const isDraft = file.path.startsWith("_drafts");
      const post = await parsePost(file, isDraft);
      if (post) {
        posts.push(post);
      }
    }
    return posts.sort((a, b) => b.date.localeCompare(a.date));
  };
  const createPost = async (title) => {
    const draftsFolder = "_drafts";
    if (!vault.getAbstractFileByPath(draftsFolder)) {
      await vault.createFolder(draftsFolder);
    }
    const filename = titleToFilename(title);
    const filepath = `${draftsFolder}/${filename}`;
    const content = `---
title: ${title}
date: ${new Date().toISOString().split("T")[0]}
categories: []
tags: []
---

Write your post here...
`;
    return await vault.create(filepath, content);
  };
  const publishPost = async (file) => {
    const filename = file.name;
    const dateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})-/);
    let newFilename = filename;
    if (!dateMatch) {
      const today = new Date().toISOString().split("T")[0];
      newFilename = `${today}-${filename}`;
    }
    const newRelativePath = `_posts/${newFilename}`;
    await vault.rename(file, newRelativePath);
    const renamedFile = vault.getAbstractFileByPath(newRelativePath);
    return renamedFile;
  };
  const unpublishPost = async (file) => {
    const filename = file.name;
    const newFilename = filename.replace(/^\d{4}-\d{2}-\d{2}-/, "");
    const newRelativePath = `_drafts/${newFilename}`;
    await vault.rename(file, newRelativePath);
    const renamedFile = vault.getAbstractFileByPath(newRelativePath);
    return renamedFile;
  };
  const deletePost = async (file) => {
    await vault.delete(file);
  };
  return {
    loadPosts,
    parsePost,
    createPost,
    publishPost,
    unpublishPost,
    deletePost
  };
}

// src/utils/date.ts
var formatDate = (dateStr) => {
  if (!dateStr)
    return "";
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
};

// src/ui/render.ts
function createRenderer() {
  const renderBlogList = (container, posts, callbacks) => {
    container.empty();
    container.addClass("jekyll-blog-view");
    const headerEl = container.createDiv({ cls: "blog-header" });
    headerEl.createEl("h3", { text: "Writing" });
    const newPostBtn = headerEl.createEl("button", { text: "New Post", cls: "mod-cta new-post-btn" });
    newPostBtn.addEventListener("click", callbacks.onNewPost);
    if (posts.length === 0) {
      container.createEl("p", {
        text: 'No posts yet. Click "New Post" to begin writing.',
        cls: "empty-state"
      });
      return;
    }
    const drafts = posts.filter((p) => p.isDraft);
    const published = posts.filter((p) => !p.isDraft);
    if (drafts.length > 0) {
      const draftsSection = container.createDiv({ cls: "posts-section" });
      const sectionHeader = draftsSection.createDiv({ cls: "section-header" });
      sectionHeader.createEl("span", { text: "Drafts", cls: "section-title" });
      sectionHeader.createEl("span", { text: `${drafts.length}`, cls: "section-count" });
      for (const post of drafts) {
        renderPostItem(draftsSection, post, () => callbacks.onPostClick(post.file));
      }
    }
    if (published.length > 0) {
      const publishedSection = container.createDiv({ cls: "posts-section" });
      const sectionHeader = publishedSection.createDiv({ cls: "section-header" });
      sectionHeader.createEl("span", { text: "Published", cls: "section-title" });
      sectionHeader.createEl("span", { text: `${published.length}`, cls: "section-count" });
      for (const post of published) {
        renderPostItem(publishedSection, post, () => callbacks.onPostClick(post.file));
      }
    }
  };
  const renderPostItem = (container, post, onClick) => {
    const postEl = container.createDiv({ cls: "post-item" });
    postEl.addEventListener("click", onClick);
    const titleEl = postEl.createDiv({ cls: "post-title" });
    titleEl.createEl("span", { text: post.title });
    if (post.excerpt) {
      const excerptEl = postEl.createDiv({ cls: "post-excerpt" });
      excerptEl.createEl("span", { text: post.excerpt });
    }
    const metaEl = postEl.createDiv({ cls: "post-meta" });
    const dateText = formatDate(post.date);
    const readingTime = getReadingTime(post.wordCount);
    metaEl.createEl("span", { text: `${dateText} \xB7 ${readingTime}` });
  };
  const getPropertyIcon = (key) => {
    const icons = {
      "title": "\u{1F4DD}",
      "date": "\u{1F4C5}",
      "categories": "\u{1F4C1}",
      "tags": "\u{1F3F7}\uFE0F"
    };
    return icons[key] || "\u2022";
  };
  const getPropertyLabel = (key) => {
    return key.charAt(0).toUpperCase() + key.slice(1);
  };
  const renderProperty = (container, key, value) => {
    const propRow = container.createDiv({ cls: "property-row" });
    const icon = getPropertyIcon(key);
    const label = getPropertyLabel(key);
    const labelEl = propRow.createEl("label", {
      text: `${icon} ${label}`,
      cls: "property-label"
    });
    if (key === "date") {
      const input = propRow.createEl("input", {
        type: "date",
        value,
        cls: "property-input"
      });
      input.setAttribute("data-property-key", key);
      input.setAttribute("data-property-type", "string");
    } else if (Array.isArray(value)) {
      const input = propRow.createEl("input", {
        type: "text",
        value: value.join(", "),
        cls: "property-input",
        placeholder: `Enter ${label.toLowerCase()}...`
      });
      input.setAttribute("data-property-key", key);
      input.setAttribute("data-property-type", "array");
    } else {
      const input = propRow.createEl("input", {
        type: "text",
        value,
        cls: "property-input",
        placeholder: `Enter ${label.toLowerCase()}...`
      });
      input.setAttribute("data-property-key", key);
      input.setAttribute("data-property-type", "string");
    }
    return propRow;
  };
  const renderTagsPills = (container, tags, allTags) => {
    const tagsArray = Array.isArray(tags) ? tags : [];
    const pillsContainer = container.createDiv({ cls: "tags-pills-container" });
    pillsContainer.setAttribute("data-property-key", "tags");
    pillsContainer.setAttribute("data-property-type", "array");
    const renderPills = () => {
      pillsContainer.empty();
      tagsArray.forEach((tag, index) => {
        const pill = pillsContainer.createDiv({ cls: "tag-pill" });
        pill.createEl("span", { text: tag, cls: "tag-text" });
        const removeBtn = pill.createEl("span", { text: "\xD7", cls: "tag-remove" });
        removeBtn.addEventListener("click", () => {
          tagsArray.splice(index, 1);
          renderPills();
        });
      });
      const inputWrapper = pillsContainer.createDiv({ cls: "tag-input-wrapper" });
      const input = inputWrapper.createEl("input", {
        type: "text",
        cls: "tag-input",
        placeholder: tagsArray.length === 0 ? "Add tags..." : ""
      });
      const datalist = inputWrapper.createEl("datalist", { attr: { id: "tags-suggestions" } });
      allTags.forEach((tag) => {
        if (!tagsArray.includes(tag)) {
          datalist.createEl("option", { attr: { value: tag } });
        }
      });
      input.setAttribute("list", "tags-suggestions");
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter" && input.value.trim()) {
          e.preventDefault();
          const newTag = input.value.trim();
          if (!tagsArray.includes(newTag)) {
            tagsArray.push(newTag);
            renderPills();
          }
        }
      });
    };
    renderPills();
    return pillsContainer;
  };
  const renderCategoriesDropdown = (container, categories, allCategories) => {
    const categoriesArray = Array.isArray(categories) ? categories : [];
    const selectContainer = container.createDiv({ cls: "categories-container" });
    selectContainer.setAttribute("data-property-key", "categories");
    selectContainer.setAttribute("data-property-type", "array");
    const input = selectContainer.createEl("input", {
      type: "text",
      cls: "property-input",
      value: categoriesArray.join(", "),
      placeholder: "Select or type categories..."
    });
    const datalist = selectContainer.createEl("datalist", { attr: { id: "categories-suggestions" } });
    allCategories.forEach((cat) => {
      datalist.createEl("option", { attr: { value: cat } });
    });
    input.setAttribute("list", "categories-suggestions");
    return selectContainer;
  };
  return {
    renderBlogList,
    renderPostItem,
    renderProperty,
    renderTagsPills,
    renderCategoriesDropdown
  };
}

// src/ui/styles.ts
var injectBlogListStyles = () => {
  const styleEl = document.getElementById("jekyll-blog-styles");
  if (styleEl)
    return;
  const style = document.createElement("style");
  style.id = "jekyll-blog-styles";
  style.textContent = `
    .jekyll-blog-view {
      padding: 16px;
    }
    .blog-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
    }
    .blog-header h3 {
      margin: 0;
      font-size: 1.5em;
      font-weight: 600;
      color: var(--text-normal);
    }
    .new-post-btn {
      font-size: 0.9em;
    }
    .posts-section {
      margin-bottom: 32px;
    }
    .section-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
      padding-bottom: 8px;
      border-bottom: 1px solid var(--background-modifier-border);
    }
    .section-title {
      font-size: 0.85em;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--text-muted);
    }
    .section-count {
      font-size: 0.85em;
      color: var(--text-muted);
    }
    .post-item {
      padding: 12px 16px;
      margin-bottom: 4px;
      cursor: pointer;
      border-radius: 4px;
      transition: background-color 0.15s ease;
    }
    .post-item:hover {
      background: var(--background-modifier-hover);
    }
    .post-title {
      font-size: 1.05em;
      font-weight: 500;
      color: var(--text-normal);
      margin-bottom: 6px;
      line-height: 1.4;
    }
    .post-excerpt {
      font-size: 0.9em;
      color: var(--text-muted);
      margin-bottom: 6px;
      line-height: 1.5;
    }
    .post-meta {
      font-size: 0.85em;
      color: var(--text-faint);
    }
    .empty-state {
      text-align: center;
      color: var(--text-muted);
      padding: 48px 20px;
      font-size: 0.95em;
    }
  `;
  document.head.appendChild(style);
};
var injectPropertiesStyles = () => {
  const styleEl = document.getElementById("jekyll-properties-styles");
  if (styleEl)
    return;
  const style = document.createElement("style");
  style.id = "jekyll-properties-styles";
  style.textContent = `
    .jekyll-properties-view {
      padding: 16px;
    }
    .status-card {
      background: var(--background-secondary);
      border-radius: 8px;
      padding: 0;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .status-info {
      margin-bottom: 24px;
    }
    .status-label {
      font-size: 0.85em;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 4px;
    }
    .status-label.draft {
      color: var(--text-muted);
    }
    .status-label.published {
      color: var(--text-accent);
    }
    .status-text {
      font-size: 0.95em;
      color: var(--text-muted);
    }
    .property-section {
      margin-bottom: 28px;
    }
    .section-title {
      font-size: 0.85em;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--text-muted);
      margin-bottom: 12px;
    }
    .property-row {
      margin-bottom: 16px;
    }
    .property-label {
      display: block;
      font-size: 0.9em;
      font-weight: 500;
      color: var(--text-muted);
      margin-bottom: 6px;
    }
    .property-input {
      width: 100%;
      padding: 10px 12px;
      border: 1px solid var(--background-modifier-border);
      border-radius: 6px;
      background: var(--background-primary);
      color: var(--text-normal);
      font-size: 0.95em;
      transition: border-color 0.15s ease;
    }
    .property-input:focus {
      outline: none;
      border-color: var(--interactive-accent);
    }
    .property-input::placeholder {
      color: var(--text-faint);
    }
    .tags-pills-container {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
      padding: 8px;
      border: 1px solid var(--background-modifier-border);
      border-radius: 6px;
      background: var(--background-primary);
      min-height: 42px;
      align-items: center;
    }
    .tag-pill {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 8px;
      background: var(--background-modifier-hover);
      border-radius: 4px;
      font-size: 0.85em;
    }
    .tag-text {
      color: var(--text-normal);
    }
    .tag-remove {
      color: var(--text-muted);
      cursor: pointer;
      font-size: 1.2em;
      line-height: 1;
      transition: color 0.15s ease;
    }
    .tag-remove:hover {
      color: var(--text-error);
    }
    .tag-input-wrapper {
      flex: 1;
      min-width: 100px;
    }
    .tag-input {
      border: none;
      background: transparent;
      outline: none;
      padding: 4px;
      font-size: 0.9em;
      color: var(--text-normal);
      width: 100%;
    }
    .tag-input::placeholder {
      color: var(--text-faint);
    }
    .categories-container {
      position: relative;
    }
    .actions-section {
      margin-top: 32px;
      padding-top: 20px;
      border-top: 1px solid var(--background-modifier-border);
      display: flex;
      flex-direction: column;
      gap: 8px;
      align-items: flex-start;
    }
    .action-link {
      font-size: 0.9em;
      color: var(--text-muted);
      cursor: pointer;
      text-decoration: none;
      transition: color 0.15s ease;
      font-weight: 400;
    }
    .action-link:hover {
      color: var(--text-normal);
    }
    .action-link.primary {
      color: var(--interactive-accent);
    }
    .action-link.primary:hover {
      color: var(--interactive-accent-hover);
    }
    .action-link.danger {
      color: var(--text-faint);
    }
    .action-link.danger:hover {
      color: var(--text-error);
    }
    .empty-state {
      text-align: center;
      color: var(--text-muted);
      padding: 48px 20px;
      font-size: 0.95em;
    }
  `;
  document.head.appendChild(style);
};

// src/modals/TitleInputModal.ts
var import_obsidian = require("obsidian");
var TitleInputModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "New Blog Post" });
    const inputContainer = contentEl.createDiv();
    inputContainer.createEl("label", { text: "Post Title" });
    const input = inputContainer.createEl("input", {
      type: "text",
      placeholder: "Enter post title..."
    });
    input.style.width = "100%";
    input.style.marginTop = "10px";
    input.style.padding = "8px";
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        this.submit(input.value);
      }
    });
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "10px";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => {
      this.onSubmit("");
      this.close();
    });
    const submitBtn = buttonContainer.createEl("button", {
      text: "Create",
      cls: "mod-cta"
    });
    submitBtn.addEventListener("click", () => {
      this.submit(input.value);
    });
    input.focus();
  }
  submit(value) {
    if (value && value.trim()) {
      this.result = value.trim();
      this.close();
      this.onSubmit(this.result);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/types.ts
var VIEW_TYPE_BLOG = "jekyll-blog-view";
var VIEW_TYPE_PROPERTIES = "jekyll-properties-view";

// src/views/BlogListView.ts
var BlogListView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.posts = [];
    this.plugin = plugin;
    this.postService = createPostService(this.app);
    this.renderer = createRenderer();
  }
  getViewType() {
    return VIEW_TYPE_BLOG;
  }
  getDisplayText() {
    return "Jekyll Blog Manager";
  }
  getIcon() {
    return "newspaper";
  }
  async onOpen() {
    await this.refresh();
  }
  async onClose() {
  }
  async refresh() {
    await this.loadPosts();
    this.render();
  }
  async loadPosts() {
    this.posts = await this.postService.loadPosts();
  }
  render() {
    const container = this.containerEl.children[1];
    this.renderer.renderBlogList(container, this.posts, {
      onPostClick: (file) => this.openPostInEditor(file),
      onNewPost: () => this.createNewPost()
    });
    injectBlogListStyles();
  }
  async openPostInEditor(file) {
    try {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
    } catch (error) {
      console.error("Failed to open file:", error);
      new import_obsidian2.Notice("Failed to open file");
    }
  }
  async createNewPost() {
    try {
      const title = await this.promptForTitle();
      if (!title)
        return;
      const file = await this.postService.createPost(title);
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
      await this.refresh();
      new import_obsidian2.Notice(`Created draft: ${title}`);
    } catch (error) {
      console.error("Create post error:", error);
      new import_obsidian2.Notice(`Failed to create post: ${error.message}`);
    }
  }
  async promptForTitle() {
    return new Promise((resolve) => {
      const modal = new TitleInputModal(this.app, (title) => {
        resolve(title || null);
      });
      modal.open();
    });
  }
};

// src/views/PropertiesView.ts
var import_obsidian3 = require("obsidian");

// src/services/git.ts
var import_child_process = require("child_process");
var import_util = require("util");
var execAsync = (0, import_util.promisify)(import_child_process.exec);
function createGitService(basePath) {
  const commitAndPush = async (message) => {
    try {
      await execAsync(`git add -A`, { cwd: basePath });
      await execAsync(`git commit -m "${message}"`, { cwd: basePath });
      await execAsync(`git push`, { cwd: basePath });
    } catch (error) {
      console.error("Failed to commit and push:", error);
      throw error;
    }
  };
  const commit = async (message) => {
    await execAsync(`git add -A`, { cwd: basePath });
    await execAsync(`git commit -m "${message}"`, { cwd: basePath });
  };
  const push = async () => {
    await execAsync(`git push`, { cwd: basePath });
  };
  return { commitAndPush, commit, push };
}

// src/services/tags.ts
function createTagService(metadataCache) {
  const getAllTagsAndCategories = async (files) => {
    const tags = /* @__PURE__ */ new Set();
    const categories = /* @__PURE__ */ new Set();
    for (const file of files) {
      const cache = metadataCache.getFileCache(file);
      const frontmatter = cache == null ? void 0 : cache.frontmatter;
      if (!frontmatter)
        continue;
      if (Array.isArray(frontmatter.tags)) {
        frontmatter.tags.forEach((tag) => {
          if (tag)
            tags.add(String(tag));
        });
      }
      if (Array.isArray(frontmatter.categories)) {
        frontmatter.categories.forEach((category) => {
          if (category)
            categories.add(String(category));
        });
      }
    }
    return { tags, categories };
  };
  const getAllTags = async (files) => {
    const { tags } = await getAllTagsAndCategories(files);
    return tags;
  };
  const getAllCategories = async (files) => {
    const { categories } = await getAllTagsAndCategories(files);
    return categories;
  };
  return { getAllTagsAndCategories, getAllTags, getAllCategories };
}

// src/services/frontmatter.ts
var parseFrontmatter = (content) => {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch)
    return {};
  const frontmatter = frontmatterMatch[1];
  const lines = frontmatter.split("\n");
  const properties = {};
  for (const line of lines) {
    const match = line.match(/^([^:]+):\s*(.*)$/);
    if (match) {
      const key = match[1].trim();
      let valueStr = match[2].trim();
      let value = valueStr;
      if (valueStr.startsWith("[") && valueStr.endsWith("]")) {
        value = valueStr.slice(1, -1).split(",").map((v) => v.trim());
      }
      properties[key] = value;
    }
  }
  return properties;
};
var updateMultipleProperties = (content, updates) => {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch)
    return content;
  let frontmatter = frontmatterMatch[1];
  const lines = frontmatter.split("\n");
  const newLines = [];
  for (const line of lines) {
    const match = line.match(/^([^:]+):\s*(.*)$/);
    if (match) {
      const key = match[1].trim();
      if (updates.hasOwnProperty(key)) {
        if (Array.isArray(updates[key])) {
          newLines.push(`${key}: [${updates[key].join(", ")}]`);
        } else {
          newLines.push(`${key}: ${updates[key]}`);
        }
      } else {
        newLines.push(line);
      }
    } else {
      newLines.push(line);
    }
  }
  const newFrontmatter = newLines.join("\n");
  return content.replace(/^---\n[\s\S]*?\n---/, `---
${newFrontmatter}
---`);
};

// src/views/PropertiesView.ts
var PropertiesView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentFile = null;
    this.properties = {};
    this.allTags = /* @__PURE__ */ new Set();
    this.allCategories = /* @__PURE__ */ new Set();
    this.plugin = plugin;
    this.postService = createPostService(this.app);
    this.gitService = createGitService(this.app.vault.adapter.basePath);
    this.tagService = createTagService(this.app.metadataCache);
    this.renderer = createRenderer();
  }
  getViewType() {
    return VIEW_TYPE_PROPERTIES;
  }
  getDisplayText() {
    return "Post Properties";
  }
  getIcon() {
    return "settings";
  }
  async onOpen() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.updateProperties();
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file === this.currentFile) {
          this.updateProperties();
        }
      })
    );
    await this.updateProperties();
  }
  async onClose() {
  }
  async updateProperties() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || !activeFile.path.startsWith("_posts/") && !activeFile.path.startsWith("_drafts/")) {
      this.currentFile = null;
      this.properties = {};
      this.render();
      return;
    }
    this.currentFile = activeFile;
    await this.loadProperties();
    this.render();
  }
  async loadProperties() {
    if (!this.currentFile)
      return;
    try {
      const content = await this.app.vault.read(this.currentFile);
      this.properties = parseFrontmatter(content);
      const blogFiles = this.app.vault.getMarkdownFiles().filter(
        (file) => file.path.startsWith("_drafts/") || file.path.startsWith("_posts/")
      );
      const { tags, categories } = await this.tagService.getAllTagsAndCategories(blogFiles);
      this.allTags = tags;
      this.allCategories = categories;
    } catch (error) {
      console.error("Failed to load properties:", error);
    }
  }
  async saveAllProperties() {
    if (!this.currentFile)
      return;
    try {
      const container = this.containerEl.children[1];
      const updates = {};
      const inputs = container.querySelectorAll("input[data-property-key]");
      inputs.forEach((input) => {
        const htmlInput = input;
        const key = htmlInput.getAttribute("data-property-key");
        const type = htmlInput.getAttribute("data-property-type");
        if (key) {
          if (type === "array") {
            updates[key] = htmlInput.value.split(",").map((v) => v.trim()).filter((v) => v);
          } else {
            updates[key] = htmlInput.value;
          }
        }
      });
      const tagsPillsContainer = container.querySelector('.tags-pills-container[data-property-key="tags"]');
      if (tagsPillsContainer) {
        const pills = tagsPillsContainer.querySelectorAll(".tag-pill .tag-text");
        const tags = [];
        pills.forEach((pill) => {
          tags.push(pill.textContent || "");
        });
        updates["tags"] = tags;
      }
      const content = await this.app.vault.read(this.currentFile);
      const newContent = updateMultipleProperties(content, updates);
      await this.app.vault.modify(this.currentFile, newContent);
      await this.gitService.commitAndPush(`save: ${this.currentFile.name}`);
      new import_obsidian3.Notice("Properties updated");
    } catch (error) {
      console.error("Failed to save properties:", error);
      new import_obsidian3.Notice("Failed to save properties");
    }
  }
  async publishPost() {
    if (!this.currentFile)
      return;
    try {
      const title = this.currentFile.basename;
      const renamedFile = await this.postService.publishPost(this.currentFile);
      await this.gitService.commitAndPush(`Publish: ${title}`);
      new import_obsidian3.Notice(`Published: ${title}`);
      this.currentFile = renamedFile;
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(renamedFile);
      setTimeout(() => {
        this.updateProperties();
        this.refreshBlogList();
      }, 100);
    } catch (error) {
      console.error("Failed to publish post:", error);
      new import_obsidian3.Notice(`Failed to publish post: ${error.message}`);
    }
  }
  async unpublishPost() {
    if (!this.currentFile)
      return;
    try {
      const title = this.currentFile.basename;
      const renamedFile = await this.postService.unpublishPost(this.currentFile);
      await this.gitService.commitAndPush(`Unpublish: ${title}`);
      new import_obsidian3.Notice(`Unpublished: ${title}`);
      this.currentFile = renamedFile;
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(renamedFile);
      setTimeout(() => {
        this.updateProperties();
        this.refreshBlogList();
      }, 100);
    } catch (error) {
      console.error("Failed to unpublish post:", error);
      new import_obsidian3.Notice(`Failed to unpublish post: ${error.message}`);
    }
  }
  async deletePost() {
    if (!this.currentFile)
      return;
    const confirmation = confirm(`Are you sure you want to delete "${this.currentFile.name}"?`);
    if (!confirmation)
      return;
    try {
      const basename = this.currentFile.basename;
      await this.postService.deletePost(this.currentFile);
      await this.gitService.commitAndPush(`Delete: ${basename}`);
      new import_obsidian3.Notice(`Deleted: ${basename}`);
      this.currentFile = null;
      this.render();
      this.refreshBlogList();
    } catch (error) {
      console.error("Failed to delete post:", error);
      new import_obsidian3.Notice("Failed to delete post");
    }
  }
  refreshBlogList() {
    const leaves = this.app.workspace.getLeavesOfType("jekyll-blog-view");
    if (leaves.length > 0) {
      const blogView = leaves[0].view;
      if (blogView.refresh) {
        blogView.refresh();
      }
    }
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("jekyll-properties-view");
    if (!this.currentFile) {
      container.createEl("p", {
        text: "Open a blog post to see details",
        cls: "empty-state"
      });
      return;
    }
    const isPublished = this.currentFile.path.startsWith("_posts/");
    const statusEl = container.createDiv({ cls: "status-info" });
    if (isPublished) {
      const dateText = formatDate(this.properties["date"]);
      statusEl.createEl("div", { text: "Published", cls: "status-label published" });
      if (dateText) {
        statusEl.createEl("div", { text: dateText, cls: "status-text" });
      }
    } else {
      statusEl.createEl("div", { text: "Draft", cls: "status-label draft" });
      statusEl.createEl("div", { text: "Not yet published", cls: "status-text" });
    }
    const postInfoSection = container.createDiv({ cls: "property-section" });
    postInfoSection.createEl("div", { text: "Post Info", cls: "section-title" });
    const postInfoProps = ["title", "date"];
    for (const key of postInfoProps) {
      if (this.properties[key] !== void 0) {
        this.renderer.renderProperty(postInfoSection, key, this.properties[key]);
      }
    }
    const orgSection = container.createDiv({ cls: "property-section" });
    orgSection.createEl("div", { text: "Organization", cls: "section-title" });
    if (this.properties["tags"] !== void 0) {
      const propRow = orgSection.createDiv({ cls: "property-row" });
      propRow.createEl("label", { text: "\u{1F3F7}\uFE0F Tags", cls: "property-label" });
      this.renderer.renderTagsPills(propRow, this.properties["tags"], this.allTags);
    }
    if (this.properties["categories"] !== void 0) {
      const propRow = orgSection.createDiv({ cls: "property-row" });
      propRow.createEl("label", { text: "\u{1F4C1} Categories", cls: "property-label" });
      this.renderer.renderCategoriesDropdown(propRow, this.properties["categories"], this.allCategories);
    }
    const actionsSection = container.createDiv({ cls: "actions-section" });
    if (isPublished) {
      const unpublishLink = actionsSection.createEl("a", {
        text: "\u2192 Unpublish",
        cls: "action-link"
      });
      unpublishLink.addEventListener("click", async (e) => {
        e.preventDefault();
        unpublishLink.textContent = "\u2192 Unpublishing...";
        await this.unpublishPost();
        unpublishLink.textContent = "\u2192 Unpublish";
      });
    } else {
      const publishLink = actionsSection.createEl("a", {
        text: "\u2192 Publish",
        cls: "action-link primary"
      });
      publishLink.addEventListener("click", async (e) => {
        e.preventDefault();
        publishLink.textContent = "\u2192 Publishing...";
        await this.publishPost();
        publishLink.textContent = "\u2192 Publish";
      });
    }
    const saveLink = actionsSection.createEl("a", {
      text: "\u2192 Save",
      cls: "action-link"
    });
    saveLink.addEventListener("click", async (e) => {
      e.preventDefault();
      saveLink.textContent = "\u2192 Saving...";
      await this.saveAllProperties();
      saveLink.textContent = "\u2192 Save";
    });
    const deleteLink = actionsSection.createEl("a", {
      text: "\u2192 Delete",
      cls: "action-link danger"
    });
    deleteLink.addEventListener("click", async (e) => {
      e.preventDefault();
      await this.deletePost();
    });
    injectPropertiesStyles();
  }
};

// src/settings/SettingTab.ts
var import_obsidian4 = require("obsidian");
var JekyllBlogSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", {
      text: "Jekyll Blog Manager"
    });
    containerEl.createEl("p", {
      text: "Posts are managed directly from the current vault using the _drafts and _posts folders."
    });
  }
};

// src/ui/workspace.ts
var configureMinimalWorkspace = () => {
  const leftRibbon = document.querySelector(".side-dock-ribbon.mod-left");
  if (leftRibbon) {
    leftRibbon.style.display = "none";
  }
  const statusBar = document.querySelector(".status-bar");
  if (statusBar) {
    statusBar.style.display = "none";
  }
  const style = document.createElement("style");
  style.id = "jekyll-minimal-workspace";
  style.textContent = `
    .view-header .view-actions {
      visibility: hidden !important;
    }
    .clickable-icon {
      visibility: hidden !important;
    }
    .workspace-tab-header-container-inner {
      display: none !important;
    }
    .metadata-container {
      display: none !important;
    }
    .frontmatter-container {
      display: none !important;
    }
  `;
  document.head.appendChild(style);
};
var cleanupWorkspace = () => {
  const style = document.getElementById("jekyll-minimal-workspace");
  if (style) {
    style.remove();
  }
};

// src/main.ts
var JekyllBlogManagerPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    this.registerView(
      VIEW_TYPE_BLOG,
      (leaf) => new BlogListView(leaf, this)
    );
    this.registerView(
      VIEW_TYPE_PROPERTIES,
      (leaf) => new PropertiesView(leaf, this)
    );
    this.addRibbonIcon("newspaper", "Jekyll Blog Manager", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-jekyll-blog-view",
      name: "Open Blog Manager",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new JekyllBlogSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      configureMinimalWorkspace();
      this.activateView();
      this.activatePropertiesView();
    });
    this.registerEvent(
      this.app.vault.on("create", () => {
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", () => {
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", () => {
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", () => {
        this.refreshViews();
      })
    );
  }
  async refreshViews() {
    const blogLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BLOG);
    for (const leaf of blogLeaves) {
      const view = leaf.view;
      await view.refresh();
    }
    const propertyLeaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_PROPERTIES);
    for (const leaf of propertyLeaves) {
      const view = leaf.view;
      await view.updateProperties();
    }
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_BLOG);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_PROPERTIES);
    cleanupWorkspace();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_BLOG);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeftLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_BLOG, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async activatePropertiesView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_PROPERTIES);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_PROPERTIES, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
